### ISSUE TITLE
Zig port

### ISSUE THREAD

**Issue by lvignoli** [sqids/sqids-spec#14]
Sqids has been ported to Zig [here](https://github.com/lvignoli/sqids-zig) with a minimal test suite.
I will refactor it into a proper package, but it's already functional as is.
Would the Sqids stewardship be willing to create a sqids/sqids-zig repository to host it?

**Comment by 4kimov** [comment]
Sounds good to me 👍 

Just a heads up: most of our initial versions are pre-production for now (eg: `v0.1.0`), because we're testing not just the implementations but also the algorithm behind it. So, don't be afraid to push breaking API changes later, if needed.

**Comment by lvignoli** [comment]
Ah okay thanks for the notice! I won't hesitate then.
