### ISSUE TITLE
Pascal implementation

### ISSUE THREAD

**Issue by dokkie8844** [sqids/sqids-spec#17]
I have created an implementation in Pascal. It works with both Free Pascal and Delphi and includes unit tests for both. Could you please make a sqids-pascal repo? I will then fork it and create a pull request.

**Comment by 4kimov** [comment]
Hi @dokkie8844, thanks for pinging. We've had [this discussion](https://github.com/paolo-rossi/sqids-delphi/issues/1) going on, but I haven't heard back anything yet.

Anyway, [repo created](https://github.com/sqids/sqids-pascal), invite sent. Feel free to push.

**Comment by dokkie8844** [comment]
Hi @4kimov, I just pushed the implementation for Free Pascal and Delphi, including all unit tests from the [specs](https://github.com/sqids/sqids-spec). I think the [sqids.org/pascal](https://sqids.org/pascal) page can be created now?

**Comment by 4kimov** [comment]
Thank you @dokkie8844, well done! 👍 

Website updated. Two quick questions for you:
1. Do the examples look correct at https://sqids.org/pascal ?
2. Do Github Actions support Pascal (to auto-run tests on every push)?

**Comment by dokkie8844** [comment]
Thanks @4kimov!  
Regarding your questions:  
  1. Yes, the examples look perfectly fine!
  2. This seems not easy to implement for the Delphi side, as a valid Delphi license is required ([info I found](https://ideasawakened.com/post/radauthenticator-part-4-build-automation-with-delphi-and-github-by-installing-a-self-hosted-runner#github-self-hosted-runner-installation)). For Free Pascal on Linux, this may be possible. This is new for me, I'll try to find out!

**Comment by dokkie8844** [comment]
The GitHub action to auto-run tests on every push seems to work now. In a private repository, I tested that a unit test failure indeed leads to a failure of this action.

**Comment by 4kimov** [comment]
I was just about to write: it's ok, if it's too complicated, let's skip. But looks like you already solved it. Very cool, thanks for all the work 💪
