### ISSUE TITLE
The incompatibility with Hashids is unacceptable

### ISSUE THREAD

**Issue by aradalvand** [sqids/sqids-spec#4]
Wouldn't it have been better to just continue Hashids (the algorithm) just under the new name and organization?!

The so-called improvements that the new algorithm provides don't in the least seem worth breaking backwards-compatibility over, sure, the code might be slightly shorter and better looking, but that's hardly relevant at all to the end user. Backwards-compatibility, however, absolutely is.

The new algorithm also apparently doesn't accept a salt like Hashids, so the user has no choice but to shuffle the the alphabet manually, which is work that they didn't have to do in the previous implementation. How this is considered an "improvement" is beyond me...

There is really no advantage to the new algorithm from the user's POV. Please seriously reconsider this decision.

Yes, the new name is better as it gets rid of the connotations of the word "hash" and the unification of all the implementations in different languages under the same organization is certainly a good thing, but the breaking compatibility with the old algorithm which is arguably the most important thing when it comes to a library like this, is genuinely unacceptable. It makes no sense. And "use it for new projects" is not a good argument, this makes people lose significant trust in this whole project, and that is not trivial, the decision to use Hashids/Sqids is essentially permenant, so trust, reliability, and future-proofness are extremely important.

Don't do this.

**Comment by 4kimov** [comment]
@aradalvand Thanks for the feedback.

The whole library *is the encoding part*, so there is no backwards-compatibility if anything in the algorithm changes. Existing Hashids libraries are not going anywhere and you're free to continue using them. The website has been [archived](https://github.com/hashids/hashids.github.io), but the docs are still available at each individual repository.

The choices for the new library were not made lightly and you can find that discussion [here](https://github.com/orgs/hashids/discussions/92). I'll close the issue for now, but feel free to follow-up if you have further questions.

**Comment by aradalvand** [comment]
@4kimov 
> The whole library is the encoding part, so there is no backwards-compatibility if anything in the algorithm changes

Well, sure, I'm just saying that the change in the algorithm wasn't really necessary, was it? The rebranding is welcome but the change in the algorithm makes this essentially a totally new library.

I read the discussion you linked to, wasn't the name "scids" better? "sqids" looks like sql (in fact I read it as "SQL IDs" the first time) and can also be thought to be an abbreviation of **sc**rambled **ID**s. The GitHub username is also [not taken](https://github.com/scids).

**Comment by 4kimov** [comment]
> the change in the algorithm makes this effectively a whole new library

It is

> is the new algorithm so radically better than the old one that it's worth essentially creating a totally new library for?

Yes

> I read the discussion you linked to, regarding the naming

I'm going to avoid discussing the name, as everyone has their own opinions
