### ISSUE TITLE
Update .NET code example on the site

### ISSUE THREAD

**Issue by aradalvand** [sqids/sqids-spec#8]
Not sure if this is the right place to post this but sqids-dotnet [v2 has just been released](https://github.com/sqids/sqids-dotnet/releases/tag/v2.0.0) which added [support for all integral numeric types](https://github.com/sqids/sqids-dotnet/pull/15) in .NET (e.g. `int`, `long`, etc.) — previously we only supported `int`.
This resulted in an API breaking change where the `SqidsEncoder` class now requires the user to specify a type argument upon instantiation; so, all three [code snippets on the website](https://sqids.org/dotnet) need to be updated:

```diff
-  var sqids = new SqidsEncoder(...
+  var sqids = new SqidsEncoder<int>(...
```

**Comment by 4kimov** [comment]
Nice, thanks for all the work on the release + the heads up on the examples. Does it look better now?

**Comment by aradalvand** [comment]
Yes, perfect, thanks!
